config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

/*Router::scope('/', function ($routes) {
    $routes->connect('/', 
        ['controller' => 'Pages', 'action' => 'display', 'home'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']
        );
    $routes->connect(
        '/:controller',
        ['action' => 'index'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']
    );
    $routes->connect(
        '/:controller/:action/*',
        [],
        ['routeClass' => 'ADmad/I18n.I18nRoute']
    );
});*/
Router::extensions(['json', 'xml']);
Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

Router::prefix('admin', function ($routes) {
    // Toutes les routes ici seront préfixées avec `/admin` et auront
    // l'élément de route prefix => admin ajouté.
    $routes->connect('/', ['controller' => 'Cars', 'action' => 'index']);
    $routes->fallbacks('DashedRoute');
});

Router::connect(
    '/verify/*',
    ['controller' => 'Users', 'action' => 'verify'],
    ['_name' => 'verify']
);
Router::connect(
    '/forgotpassword/*',
    ['controller' => 'Users', 'action' => 'forgotpassword'],
    ['_name' => 'forgotpassword']
);
Router::connect(
    '/login',
    ['controller' => 'Users', 'action' => 'login'],
    ['_name' => 'login']
);
Router::connect(
    '/register',
    ['controller' => 'Users', 'action' => 'register'],
    ['_name' => 'register']
);
/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Reservation.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Reservation Entity.
 *
 * @property int $id
 * @property \Cake\I18n\Time $from_date
 * @property \Cake\I18n\Time $from_time
 * @property \Cake\I18n\Time $to_date
 * @property \Cake\I18n\Time $to_time
 * @property string $pickup_location
 * @property string $return_location
 * @property int $user_id
 * @property \App\Model\Entity\User $user
 * @property int $confirmed
 * @property \App\Model\Entity\Reservationarticle[] $reservationarticles
 */
class Reservation extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false,
    ];
}

src/Model/Table/ReservationsTable.php
<?php
namespace App\Model\Table;

use App\Model\Entity\Reservation;
use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Reservations Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Users
 * @property \Cake\ORM\Association\HasMany $Reservationarticles
 */
class ReservationsTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('reservations');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->belongsTo('Users', [
            'foreignKey' => 'user_id',
            'strategy' => 'select'
        ]);

        $this->belongsTo('Guests', [
            'foreignKey' => 'guest_id',
            'strategy' => 'select'
        ]);

        $this->belongsToMany('Cars', [
            'joinTable' => 'carsreservations'
        ]);
        $this->belongsToMany('Extras', [
            'joinTable' => 'extrasreservations'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmpty('id', 'create');

        $validator
            ->date('from_date')
            ->requirePresence('from_date', 'create')
            ->notEmpty('from_date');

        $validator
            ->time('from_time')
            ->requirePresence('from_time', 'create')
            ->notEmpty('from_time');

        $validator
            ->date('to_date')
            ->requirePresence('to_date', 'create')
            ->notEmpty('to_date');

        $validator
            ->time('to_time')
            ->requirePresence('to_time', 'create')
            ->notEmpty('to_time');

        $validator
            ->requirePresence('pickup_location', 'create')
            ->notEmpty('pickup_location');

        $validator
            ->requirePresence('return_location', 'create')
            ->notEmpty('return_location');

        $validator
            ->requirePresence('code', 'create')
            ->allowEmpty('code');

        $validator
            ->integer('confirmed')
            ->allowEmpty('confirmed');

        $validator
            ->integer('rejected')
            ->allowEmpty('rejected');
        
        $validator
            ->integer('canceled')
            ->allowEmpty('canceled');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['user_id'], 'Users'));
        $rules->add($rules->existsIn(['guest_id'], 'Guests'));
        return $rules;
    }
}

src/Controller/Admin/ReservationsController.php
<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AppController;
use Cake\Event\Event;

/**
 * Reservations Controller
 *
 * @property \App\Model\Table\ReservationsTable $Reservations
 */
class ReservationsController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        //$this->Auth->allow(['add','status']);
    }
    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index($status = null)
    {
        $reservations = $this->Reservations->find()
                                           ->contain([
                                                'Guests',
                                                'Cars'=>[
                                                    'Medias'=>[
                                                        'sort'=>['primary_img'=>'DESC']
                                                    ]
                                                ],
                                                'Extras',
                                                'Users'
                                                ])
                                           
                                           ->where(['confirmed'=>'1'])
                                           ->order(['id'=>'DESC']);
        $title = "List des reservations confirmées";

        $this->loadModel('Extras');
        $extras = $this->Extras->find()->combine('id', 'name_fr');;
        //print_r($reservations); die();
        $this->set(compact('reservations','title','extras','status'));
        $this->set('_serialize', ['reservations']);
    }

    public function rejected($status = null)
    {
        $reservations = $this->Reservations->find()
                                           ->contain([
                                                'Guests',
                                                'Cars'=>[
                                                    'Medias'=>[
                                                        'sort'=>['primary_img'=>'DESC']
                                                    ]
                                                ],
                                                'Extras',
                                                'Users'
                                                ])
                                           
                                           ->where(['rejected'=>'1'])
                                           ->order(['id'=>'DESC']);
        $title = "List des reservations rejetées";

        $this->loadModel('Extras');
        $extras = $this->Extras->find()->combine('id', 'name_fr');;
        //print_r($reservations); die();
        $this->set(compact('reservations','title','extras','status'));
        $this->set('_serialize', ['reservations']);
    }

    public function requests($status = null)
    {
        $reservations = $this->Reservations->find()
                                           ->contain([
                                                'Guests',
                                                'Cars'=>[
                                                    'Medias'=>[
                                                        'sort'=>['primary_img'=>'DESC']
                                                    ]
                                                ],
                                                'Extras',
                                                'Users'
                                                ])
                                           
                                           ->where(['confirmed'=>'0','rejected'=>'0','canceled'=>'0'])
                                           ->order(['id'=>'DESC']);

        $title = "List des nouvelles demandes de reservations";

        $this->loadModel('Extras');
        $extras = $this->Extras->find()->combine('id', 'name_fr');;
        //print_r($reservations); die();
        $this->set(compact('reservations','title','extras','status'));
        $this->set('_serialize', ['reservations']);
    }

    public function edit($id = null)
    {
        //print_r($this->referer()); die();
        $status = true;
        $reservation = $this->Reservations->get($id, [
            'contain' => []
        ]);
        $data = ['from_date' => $this->request->data['from_date'],
                 'from_time' => $this->request->data['from_time'],
                 'to_date' => $this->request->data['to_date'],
                 'to_time' => $this->request->data['to_time'],
                 'pickup_location' => $this->request->data['pickup_location'],
                 'return_location' => $this->request->data['return_location']
                 ];

        $extras = $this->request->data['extras'];

        if ($this->request->is(['patch', 'post', 'put'])) {
            $reservation = $this->Reservations->patchEntity($reservation, $data);
            if ($this->Reservations->save($reservation)) {
                echo "success save reservation";
                $this->loadModel('Extrasreservations');
                $resextras = $this->Extrasreservations->find()
                                                      ->where(['reservation_id'=>$id])
                                                      ->toArray();
                if (!empty($resextras)) {
                    if(!$this->Extrasreservations->deleteAll(['reservation_id' => $id])){
                        $status = false;
                    }
                }
                
                foreach ($extras as $ex) {
                    $extra = $this->Extrasreservations->newEntity();
                    $extra = $this->Extrasreservations->patchEntity($extra, ['extra_id'=>$ex, 'reservation_id' => $id]);
                    if(!$this->Extrasreservations->save($extra)){
                        $status = false;
                        break;
                    }
                }
            } else {
                $status = false;
            }

            return $this->redirect($this->referer().'?status='.$status);
        }
    }

    public function cancel($id){
        $status = true;
        $reservation = $this->Reservations->get($id, [
            'contain' => []
        ]);

        $cancel = 0;
        if ($reservation->canceled == 0) {
            $cancel = 1;
        }

        $reservation = $this->Reservations->patchEntity($reservation, ['canceled'=>$cancel]);
        //print_r($reservation); die();
        if (!$this->Reservations->save($reservation)) {
            $status = false;
        }
        return $this->redirect(['action' => 'index', $status]);
    }

    public function confirm($id){
        $reservation = $this->Reservations->get($id, [
            'contain' => []
        ]);
         $reservation = $this->Reservations->patchEntity($reservation, ['confirmed'=>'1','rejected'=>'0','canceled'=>'0']);

         if (!$this->Reservations->save($reservation)) {
            $this->Flash->error('Une Erreur est Survenue lors de la confirmation de la reservation, veuillez reessayer plutard');
         }

         return $this->redirect($this->referer());
    }

    public function reject($id){
        $reservation = $this->Reservations->get($id, [
            'contain' => []
        ]);
         $reservation = $this->Reservations->patchEntity($reservation, ['confirmed'=>'0','rejected'=>'1','canceled'=>'0']);

         if (!$this->Reservations->save($reservation)) {
            $this->Flash->error('Une Erreur est Survenue lors du rejet de la reservation, veuillez reessayer plutard');
         }

         return $this->redirect($this->referer());
    }
    /**
     * Delete method
     *
     * @param string|null $id Reservation id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $reservation = $this->Reservations->get($id);
        if ($this->Reservations->delete($reservation)) {
            $this->Flash->success(__('The reservation has been deleted.'));
        } else {
            $this->Flash->error(__('The reservation could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }

    private function generatecode(){
        $chars = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','0','1','2','3','4','5','6','7','8','9'];

        $str = '';
        for ($i=0; $i < 8; $i++) { 
            $str .= $chars[array_rand($chars, 1)];
        }
        //echo '-----> string '.$str;
        return $str;
    }

    private function unique(){
        //echo "entred unique";
        while (true) {
            $str = $this->generatecode();
            //echo '-----> string from unique '.$str;
            $resbycode = $this->Reservations->find()
                           ->where(['code'=>$str])
                           ->toArray();
            //print_r($code); die();
            if (empty($resbycode)) {
                break;
            }
        }
        //echo 'unique code ----> '.
        //print_r($code);
        return $str;
    }

}

src/Template/Reservations/add.ctp
<?php use Cake\I18n\I18n; ?>
<?php $lang = $this->request->session()->read('lang'); ?>
<?php if ($lang == 'fr') {
    I18n::locale('fr_FR');
} ?>

<div id="content" class="sidebar-middle" style="margin-left: 10%; min-width: 80%;margin-top: 15px;">
    <div class="widget main-widget product-widget" style="min-height: 460px;">
    	<center>
            <?= $this->Html->image('happy.jpg',['style'=>'width: 170px;margin-top: 30px;margin-bottom: 30px;']); ?>
        </center>
        <center class="txt">
            <?= __('Your request has been successfully submitted and we will contact you once your request is processed') ?>
        </center>
        <center class="txt">
            <?= __('You can check the status of your request at any time using the code bellow:') ?>
        </center>
        <br><br>
        <center>
            <span class="code"><?= $rescode; ?></span>
        </center>
        <br><br>
        <center class="txt">
            <?= __('Please be warrned that the request is not confirmed until you get a call or an email from us.') ?>
        </center>
        <center class="txt">
            <?= __('You can use').' '.$this->Html->link(__('this link'),['controller'=>'Reservations', 'action'=>'status']).' '.__('to check the status of your request or take a look at our').' '.$this->Html->link(__('available cars'),['controller'=>'Cars', 'action'=>'index']) ?>
        </center>
        <br><br>
    </div>
</div>

<style type="text/css">
    .code{
        font-size: 50px;
        font-weight: bold;
        color: #000;
    }
    .txt{
        font-size: 15px;
    }
</style>

src/Template/Reservations/status.ctp
<?php use Cake\I18n\I18n; ?>
<?php $lang = $this->request->session()->read('lang'); ?>
<?php if ($lang == 'fr') {
    I18n::locale('fr_FR');
} ?>
<?php //print_r($reservation); die(); ?>
<div id="content" class="sidebar-middle" style="margin-left: 10%; min-width: 80%;margin-top: 15px;">
    <div class="widget main-widget product-widget" style="min-height: 460px;">
    	<center style="margin-top: 40px; margin-bottom: 30px; margin-left: 20px;">
    		<?= $this->Form->create(null, ['url'=>['controller'=>'Reservations', 'action'=>'status']]);?>
            <span>
            <input type="text" name="code" class="input_placeholder" placeholder="<?= __('Enter your Code') ?>" required="required">
            </span>
            <span>
            <input type="submit" class='orange_button form-continue' value="<?= __('Check') ?>">
            </span>
            <?= $this->Form->end() ?>
    	</center>
        <?php if (isset($reservation)) :?>
            <h4>
                <?= __('Customer Personal Informations') ?>
            </h4>
            <div id="guestinfo">
                <span><?= ucfirst($reservation->guest->first_name)?> </span>
                <span> <?= ucfirst($reservation->guest->last_name)?></span>
            </div>
            <h4>
                <?= __('Car Informations') ?>
            </h4>
            <div id="carinfo" class="widget main-widget product-widget">
                <?php foreach ($reservation->cars as $car) :?>
                        <div class="post">
                            <div class="main-block_container">
                                <div class="additional-block_container">
                                    <div class="main-block">                                    
                                        <div class="product-img">
                                            <?= $this->Html->image("cars/".$car->medias[0]->name,['class'=>'grow','style'=>'width: 180px']);?>
                                        </div>
                                        <div class="product-info">
                                            <h3 class="entry-format"><?= $car->brand->name." ".$car->model->name; ?> <span>|  <?= ucfirst($car->type->{'name_'.$lang}); ?></span></h3>
                                            <div class="features">
                                                <p><?= $this->Html->image('icons/passengers.png')?>
                                                <?= $car->passengers; ?> <?= __('passengers') ?></p>
                                                <?php if ($car->auto == 1): ?>
                                                    <p>
                                                        <?= $this->Html->image('icons/autotransmission.png')?> 
                                                        <?= __('automatic transmission') ?>
                                                    </p>
                                                <?php endif ?>
                                                <?php if ($car->airconditioning): ?>
                                                    <p>
                                                        <?= $this->Html->image('icons/airconditioning.png')?> 
                                                        <?= __('air conditioning') ?>
                                                    </p>
                                                    
                                                <?php endif ?>
                                                <p>
                                                    <?= $this->Html->image('icons/fuel.png')." ".$car->fuel->{'name_'.$lang}?>
                                                </p>
                                            </div>
                                            <?php if (!empty($car->{'details_'.$lang})): ?>
                                                <div class="details">
                                                    <div class="view-details">[+] <?= __('View car details'); ?></div>
                                                    <div class="close-details">[-] <?= __('Close car details'); ?></div>
                                                    <span class="details-more">
                                                        <?= $car->{'details_'.$lang} ?>
                                                    </span>
                                                </div>
                                            <?php endif ?>
                                        </div>                              
                                    </div>
                                    <div class="additional-block">
                                        <table>
                                            <tr>
                                                <td class="title">
                                                    <?= __('Pick-up Date') ?>
                                                </td>
                                                <td>:</td>
                                                <td class="val">
                                                <?php 
                                                $from_date = ($lang == 'fr') ? $reservation->from_date->i18nFormat('yyyy-MM-dd') : $reservation->from_date->i18nFormat('dd-MM-yyyy') ; 

                                                ?>
                                                <?= $from_date.' '.__('At').' '.$reservation->from_time->i18nFormat('HH:mm') ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="title">
                                                    <?= __('Drop-off Date') ?>   
                                                </td>
                                                <td>:</td>
                                                <td class="val">
                                                <?php 
                                                $to_date = ($lang == 'fr') ? $reservation->to_date->i18nFormat('yyyy-MM-dd') : $reservation->to_date->i18nFormat('dd-MM-yyyy') ; 
                                                ?>
                                                
                                                    <?= $to_date.' '.__('At').' '.$reservation->to_time->i18nFormat('HH:mm'); ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="title"><?= __('Pick-up Location') ?></td>
                                                <td>:</td>
                                                <td class="val">
                                                    <?= $reservation->pickup_location; ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td class="title"><?= __('Drop-off Location') ?></td>
                                                <td>:</td>
                                                <td class="val">
                                                    <?= $reservation->return_location; ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </div>                                  
                            </div>
                            <div class="clear"></div>
                        </div>
                <?php endforeach; ?>
            </div>
            <h4>
                <?= __('Extras Informations') ?>
            </h4>
            <div id="extrasinfo" class="widget main-widget product-widget">
                <?php foreach ($reservation->extras as $extra) :?>
                    <div class="post">
                            <div class="main-block_container">
                                <div class="additional-block_container" style="background: none;">
                                    <div class="main-block">                                    
                                        <div class="product-img extra">
                                            <?= $this->Html->image("extras/".$extra->img,['class'=>'grow']);?>
                                        </div>
                                        <div class="product-info">
                                            <h3 class="entry-format"><?= $extra->{'name_'.$lang} ?></h3>
                                            <div class="features">

                                            </div>
                                            <?php if (!empty($extra->{'details_'.$lang})): ?>
                                                <div class="details">
                                                    <div class="view-details">[+] <?= __('View car details'); ?></div>
                                                    <div class="close-details">[-] <?= __('Close car details'); ?></div>
                                                    <span class="details-more">
                                                        <?= $extra->{'details_'.$lang} ?>
                                                    </span>
                                                </div>
                                            <?php endif ?>
                                        </div>                              
                                    </div>
                                </div>                                  
                            </div>
                            <div class="clear"></div>
                        </div>
                <?php endforeach; ?>
            </div>
            <h4>
                <?= __('Request Status') ?>
            </h4>
            <center>
                <div id="status">
                    <?php if ($reservation->confirmed == 1) {

                        echo __('We\'re happy to inform you that your request has been Confirmed, you will be contacted by phone or email to complete the process');
                    }elseif ($reservation->rejected == 1) {
                        echo __('We\'re very sorry to inform you that your request could not be confirmed, please feel free to'). $this->Html->link(__('choose from our cars'),['controller'=>'Cars','action'=>'index']).('and make another request');
                    }else{
                        echo __('Your request has not been reviewed yet, you will be contacted once an agent has confimed your request');
                    } ?>
                </div>
            </center>
        <?php else: ?>
            <center style="font-size: 14px;">
            <?= '<span class="notice">'.__('Notice').'</span> : '.__('The code is an alphanumerical case sensitive string, please make sur to write it correctlly') ?>
            </center>
        <?php endif; ?>
    </div>
</div>
<style type="text/css">
.notice{
    font-weight: bold;
    text-decoration: underline;
}
input.input_placeholder {
    padding-left: 15px;
    width: 170px;
}

.product-widget .main-block{
    float: none;
}

.product-widget .additional-block{
    padding: 0px 0px 0px 0px;
    width: 100%;
}
table{
    text-align: left;
    margin-left: 5px;
}
td {
    padding-left: 3px;
    padding-bottom: 10px;
    padding-right: 3px;
}
#carinfo{
    width: 90%; 
    margin-left: 5%;
}
#extrasinfo {
    width: 90%; 
    margin-left: 5%;
}

#guestinfo {
    margin-left: 5%;
    font-size: 30px;
    font-family: fantasy;
}
.extra img{
    max-width: 100px;
}

.main-block_container {
    width: 453px;
}
h4 {
    width: 90%;
    margin-left: 3%;
    margin-top: 35px;
    margin-bottom: 15px;
    font-size: 14px !important;
}

.title {
    font-size: 15px;
    font-weight: bold;
}
.val {
    font-size: 15px;
}

#status{
    font-size: 30px;
    width: 80%;
    font-family: initial;
    margin-top: 20px;
    margin-bottom: 40px;
    line-height: 1.2;
}
</style>