config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass('DashedRoute');

/*Router::scope('/', function ($routes) {
    $routes->connect('/', 
        ['controller' => 'Pages', 'action' => 'display', 'home'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']
        );
    $routes->connect(
        '/:controller',
        ['action' => 'index'],
        ['routeClass' => 'ADmad/I18n.I18nRoute']
    );
    $routes->connect(
        '/:controller/:action/*',
        [],
        ['routeClass' => 'ADmad/I18n.I18nRoute']
    );
});*/
Router::extensions(['json', 'xml']);
Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks('DashedRoute');
});

Router::prefix('admin', function ($routes) {
    // Toutes les routes ici seront préfixées avec `/admin` et auront
    // l'élément de route prefix => admin ajouté.
    $routes->connect('/', ['controller' => 'Cars', 'action' => 'index']);
    $routes->fallbacks('DashedRoute');
});

Router::connect(
    '/verify/*',
    ['controller' => 'Users', 'action' => 'verify'],
    ['_name' => 'verify']
);
Router::connect(
    '/forgotpassword/*',
    ['controller' => 'Users', 'action' => 'forgotpassword'],
    ['_name' => 'forgotpassword']
);
Router::connect(
    '/login',
    ['controller' => 'Users', 'action' => 'login'],
    ['_name' => 'login']
);
Router::connect(
    '/register',
    ['controller' => 'Users', 'action' => 'register'],
    ['_name' => 'register']
);
/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Table/MessagesTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Messages Model
 *
 * @property \Cake\ORM\Association\BelongsTo $ParentMessages
 * @property \Cake\ORM\Association\HasMany $ChildMessages
 *
 * @method \App\Model\Entity\Message get($primaryKey, $options = [])
 * @method \App\Model\Entity\Message newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Message[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Message|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Message patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Message[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Message findOrCreate($search, callable $callback = null)
 */
class MessagesTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('messages');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->belongsTo('FromUser', [
            'className' => 'Users',
            'propertyName'=>'fromUser',
            'foreignKey' => 'from_user'
        ]);
        $this->belongsTo('ToUser', [
            'className' => 'Users',
            'propertyName'=>'toUser',
            'foreignKey' => 'to_user'
        ]);
        $this->belongsTo('ParentMessages', [
            'className' => 'Messages',
            'foreignKey' => 'parent_id'
        ]);
        $this->hasMany('ChildMessages', [
            'className' => 'Messages',
            'foreignKey' => 'parent_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->uuid('id')
            ->allowEmpty('id', 'create');

        $validator
            ->allowEmpty('full_name');

        $validator
            ->email('email')
            ->allowEmpty('email');

        $validator
            ->requirePresence('subject', 'create')
            ->notEmpty('subject');

        $validator
            ->requirePresence('message', 'create')
            ->notEmpty('message');

        $validator
            ->dateTime('sent_at')
            ->allowEmpty('sent_at');

        $validator
            ->uuid('from_user')
            ->allowEmpty('from_user');

        $validator
            ->uuid('to_user')
            ->allowEmpty('to_user');

        $validator
            ->integer('is_read')
            ->allowEmpty('is_read');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->existsIn(['parent_id'], 'ParentMessages'));

        return $rules;
    }
}

src/Controller/Admin/MessagesController.php
<?php
namespace App\Controller\Admin;

use App\Controller\Admin\AppController;

/**
 * Sliders Controller
 *
 * @property \App\Model\Table\SlidersTable $Sliders
 */
class MessagesController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $messages = $this->Messages->find()
                                         ->contain(['FromUser','ChildMessages'])
                                         ->where(['is_read'=>'0'])
                                         ->andWhere(function ($exp, $q) {
                                                return $exp->isNull('Messages.to_user');
                                            })
                                         ->order(['Messages.sent_at']);
        $title = "Gestion des Messages non Lus";
        $this->set(compact('messages','title'));
    }

    public function old()
    {
        $messages = $this->Messages->find()
                                   ->contain(['FromUser','ChildMessages'])
                                   ->where(['is_read'=>'1'])
                                   ->andWhere(function ($exp, $q) {
                                          return $exp->isNull('Messages.to_user');
                                      })
                                   ->order(['Messages.sent_at']);
        $title = "Gestion des anciens Messages";
        $this->set(compact('messages','title'));
    }
    /**
     * Delete method
     *
     * @param string|null $id Slider id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'get']);
        $message = $this->Messages->get($id);
        if ($this->Messages->delete($message)) {
            $this->Flash->success(__('The message has been deleted.'));
        } else {
            $this->Flash->error(__('The message could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }

    public function markasread(){
        if ($this->request->is('post')) {
            $message = $this->Messages->get($this->request->data['id'], [
                'contain' => []
            ]);
            $message = $this->Messages->patchEntity($message, ['is_read'=>'1']);
            if($this->Messages->save($message)){
                echo "true";
            }else{ print_r($message); }
        }
        $this->autoRender = false;
    }

    public function conversation($id){
        $message = $this->Messages->get($id, [
                'contain' => ['ChildMessages'=>[
                                'sort'=>'ChildMessages.sent_at'
                                ],
                              'FromUser'
                              ]
            ]);

        $message = $this->Messages->patchEntity($message, ['is_read'=>'1']);
        if($this->Messages->save($message)){
                $this->Messages->query()
                               ->update()
                               ->set(['is_read' => '1'])
                               ->where(['parent_id' => $message->id, 'from_user !='=>$this->request->session()->read('Auth.User.id')])
                               ->execute();
            }else{ print_r($message); }
        $title = "Conversation";
        $this->set(compact('message','title'));
    }

    public function addanswer(){
        if ($this->request->is('post')) {
            //IF no user id was sent an user is logged (anonymous users must provide an email) then add the logged user id as the user_id for the message
            if (empty($this->request->data['from_user']) && empty($this->request->data['email'])) {
                $this->request->data['from_user'] = $this->request->session()->read('Auth.User.id');
            }
            //print_r($this->request->data); die();
            $message = $this->Messages->newEntity();
            $message = $this->Messages->patchEntity($message, $this->request->data);
            if($this->Messages->save($message)){
                echo "success";
            }else{
                print_r($message);
            }
        }
        $this->autoRender = false;
    }
}

src/Controller/MessagesController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Messages Controller
 *
 * @property \App\Model\Table\MessagesTable $Messages
 */
class MessagesController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $messages = $this->Messages
                         ->find()
                         ->where(['Messages.to_user'=>$this->request->session()->read('Auth.User.id')])
                         ->orWhere(['Messages.from_user'=>$this->request->session()->read('Auth.User.id')])
                         ->contain(['FromUser', 'ParentMessages'=>[
                                                    'ChildMessages'=>[
                                                        'sort'=>['sent_at'=>'DESC']
                                                    ]
                                                ]
                                            ])
                         ->order(['Messages.sent_at'])
                         ->group(['Messages.parent_id']);
        //print_r($messages->toArray()); die();
        $this->loadModel('Cars');
        $cars = $this->Cars->find()
                           ->contain([
                                'Brands',
                                'Models',
                                'Types',
                                'Fuels',
                                'Medias'=>[
                                    'sort'=>[
                                        'primary_img'=>'DESC',
                                        ]
                                    ],
                                'Prices'=>[
                                    'sort'=>[
                                        'price_mad'=>'ASC'
                                    ]
                                ]
                            ])
                           ->where(['published'=>'1'])
                           ->order('RAND()')
                           ->limit(3)
                           ->toArray();
        $this->set(compact('messages','cars'));
        $this->set('_serialize', ['messages']);
    }

    /**
     * View method
     *
     * @param string|null $id Message id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $message = $this->Messages->get($id, [
            'contain' => ['Users', 'ParentMessages', 'ChildMessages']
        ]);

        $this->set('message', $message);
        $this->set('_serialize', ['message']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $message = $this->Messages->newEntity();
        if ($this->request->is('post')) {
            $message = $this->Messages->patchEntity($message, $this->request->data);
            if ($this->Messages->save($message)) {
                $this->Flash->success(__('The message has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The message could not be saved. Please, try again.'));
            }
        }
        $users = $this->Messages->Users->find('list', ['limit' => 200]);
        $parentMessages = $this->Messages->ParentMessages->find('list', ['limit' => 200]);
        $this->set(compact('message', 'users', 'parentMessages'));
        $this->set('_serialize', ['message']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Message id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $message = $this->Messages->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $message = $this->Messages->patchEntity($message, $this->request->data);
            if ($this->Messages->save($message)) {
                $this->Flash->success(__('The message has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The message could not be saved. Please, try again.'));
            }
        }
        $users = $this->Messages->Users->find('list', ['limit' => 200]);
        $parentMessages = $this->Messages->ParentMessages->find('list', ['limit' => 200]);
        $this->set(compact('message', 'users', 'parentMessages'));
        $this->set('_serialize', ['message']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Message id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $message = $this->Messages->get($id);
        if ($this->Messages->delete($message)) {
            $this->Flash->success(__('The message has been deleted.'));
        } else {
            $this->Flash->error(__('The message could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Messages/index.ctp
<?php use Cake\I18n\I18n; ?>
<?php $lang = $this->request->session()->read('lang'); ?>
<?php if ($lang == 'fr') {
    I18n::locale('fr_FR');
} ?>
<div id="main">
    <div id="primary" style="background: none;">   
		<aside class="sidebar-left"> 
		    <div class="widget">

		        <h3 class="widget-title">
		            <?= $this->Html->image('icons/orderinfo.png'); ?>
		            <?= __('Top Rented Cars') ?>
		        </h3>
		        <?php foreach ($cars as $car) : ?>
		        <h4>
		        <?php 
		            $price = ($lang == 'fr') ?  $car->prices[0]->price_euro.'€': '$'.$car->prices[0]->price_usd ;
		        ?>
		        <?= __('Rent this car for only').'<span class="car-price">'.$price.'</span>('.$car->prices[0]->price_mad.' MAD )' ?>
		        </h4>
		        <div class="widget-content main-block product-widget-mini">                             
		            <div class="product-img custom-img" style='width: 130px'>
		                <?= $this->Html->image('cars/'.$car->medias[0]->name,['style'=>'width: 130px']); ?>
		            </div>
		            <div class="product-info">
		                <div class="entry-format">
		                    <div><?= ucfirst($car->brand->name)." ".ucfirst($car->model->name)?></div>
		                    <span><?= ucfirst($car->type->{'name_'.$lang}) ?></span>
		                </div>
		                <div class="features">
		                    <p><?= $this->Html->image('icons/passengers.png')?>
		                    <?= $car->passengers; ?> <?= __('passengers') ?></p>
		                    <?php if ($car->auto == 1): ?>
		                        <p>
		                            <?= $this->Html->image('icons/autotransmission.png')?> 
		                            <?= __('automatic transmission') ?>
		                        </p>
		                    <?php endif ?>
		                    <?php if ($car->airconditioning): ?>
		                        <p>
		                            <?= $this->Html->image('icons/airconditioning.png')?> 
		                            <?= __('air conditioning') ?>
		                        </p>
		                        
		                    <?php endif ?>
		                    <p>
		                        <?= $this->Html->image('icons/fuel.png')." ".$car->fuel->{'name_'.$lang}?>
		                    </p>
		                </div>
		                <?php if (!empty($car->{'details_'.$lang})): ?>
		                    <div class="details">
		                        <div class="view-details">[+] <?= __('View car details'); ?></div>
		                        <div class="close-details">[-] <?= __('Close car details'); ?></div>
		                        <span class="details-more">
		                            <?= $car->{'details_'.$lang} ?>
		                        </span>
		                    </div>
		                <?php endif ?>
		            </div>
		        </div>
		        <?php endforeach; ?>

		    </div>                                                          
		</aside>  
		<div id="content" class="sidebar-middle" style="margin-left: 8px;">
		    <div class="widget main-widget product-widget" style="min-height: 460px;">
		    	<div class="pg-title">
				    <h2>
				    	<?= __('Your Messages'); ?>
				    </h2>
				    <div class="separator"></div>
				</div>
			    <div class="widget-content-range">
			    	<div class="inbox">
				    	<div class="column column-obj">
				    		<div class="inbox-head"></div>
				    		<div>
				    		<?php foreach ($messages as $msg) : ?>
				    		<div class="msg-object" id="<?= $msg->id; ?>">
					    		<div style="display: inline-block; width: 80%;margin-left: 4%;">
					    			<div class="msg-title">
					    				<?= $msg->subject; ?>
					    			</div>
					    			<div class="msg-short">
					    				<?php if (strlen($msg->message) > 50){
					    					echo substr($msg->message, 0, 49).'...';
					    				}else{
					    					echo $msg->message;
					    				} ?>
					    			</div>
				    			</div>
				    			<div class="msg-del">
				    				x
				    			</div>
				    		</div>
				    		<?php endforeach; ?>
				    		</div>
				    	</div>
				    	<div class="column column-content">
				    		<div class="inbox-head">
				    			<span class="helper"></span>
				    			<?= $this->Html->image('user.png', ['style'=>'vertical-align: middle; width: 30px;']); ?>
				    		</div>
				    		<div class="messages-box">
					    		<?php foreach ($messages as $key=>$msg) : ?>
						    		<div class="msg-content <?= ($key==0)? 'active' : 'hidden'?>" id="content_<?= $msg->id; ?>" >
						    			<?php if (!empty($msg->parent_message)) :?>
							    			<?php foreach ($msg->parent_message->child_messages as $cm) : ?>
							    				<div class="<?= ($cm->from_user == $this->request->session()->read('Auth.User.id'))? 'admin' : 'usr' ?>">
							    					<p>
							    						<?= (strlen($msg->message) > 50)? $cm->message; ?>
							    						<span class="send_time">
							    							<?= ($lang == 'fr')? $msg->sent_at->i18nFormat('dd/MM/yyyy HH:mm') : $msg->sent_at->i18nFormat('yyyy/MM/dd HH:mm'); ?>
							    						</span>
							    					</p>
							    				</div>
							    			<?php endforeach ?>
							    		<?php else: ?>
							    				<div class="<?= ($msg->from_user == $this->request->session()->read('Auth.User.id'))? 'admin' : 'usr' ?>">
							    					<p>
							    						<?= $msg->message; ?>
							    						<span class="send_time">
							    							<?= ($lang == 'fr')? $msg->sent_at->i18nFormat('dd/MM/yyyy HH:mm') : $msg->sent_at->i18nFormat('yyyy/MM/dd HH:mm'); ?>
							    						</span>
							    					</p>
							    				</div>
						    			<?php endif; ?>
						    		</div>
					    		<?php endforeach ?>
				    		</div>
				    		<div class="replay-box">
				    			<table style="width: 95%;margin-left: auto; margin-right: auto;">
				    				<tr>
				    					<td>
				    						<textarea class="txtarea"></textarea>
				    					</td>
				    					<td style="width: 30px">
				    						<button class="orange_btn send_btn">></button>
				    					</td>
				    				</tr>
				    			</table>
				    		</div>
				    	</div>
			    	</div>
			    	
			    </div>
		    </div>
		</div>
    </div>
</div>
<script type="text/javascript">
$(document).on('click', '.msg-object', function(){
	var id = $(this).prop('id');
	$('.msg-content').removeClass('active');
	$('.msg-content').addClass('hidden');
	$('#content_'+id).removeClass('hidden');
	$('#content_'+id).addClass('active');
})
</script>
<style type="text/css">
.column-content{
	width: 65%; 
	position: relative;
}
.column-obj{
	width: 35%;
	overflow-y: auto;
}
.helper{
	height: 100%;
    vertical-align: middle;
    display: inline-block;
}
.inbox-head{
	width: 100%;
	height: 50px;
	border-bottom: 1px black solid;
}
.send_time{
	display: block;
	font-size: 11px;
	margin-top: 10px;
	color: #ababab
}
button.orange_btn{
	border: 1px solid #cc692f;
    background: #f08643;
    color: #fff;
}
button.orange_btn:hover{
	cursor: pointer;
	background: #ec702f;
}
.send_btn{
	display: inline-block;
	width: 100%; 
	height: 86px;
	vertical-align: middle;
}
.replay-box{
	position: absolute;
	bottom: 0;
	width: 100%;
	padding-top: 3px;
	padding-bottom: 7px;
	box-shadow: white 0px -5px 20px 0px;
}
.msg-object{
	background-color: grey;
	height: 70px;
	cursor: pointer;
}
.msg-del{
	display: inline-block;
    height: 70px;
    width: 16%;
    float: right;
    text-align: center;
    line-height: 70px;
}
.inbox{
	width: 95%; 
	margin-left: auto;
    margin-right: auto;
	border: 1px solid black;
	display: flex;
	padding: 5px;
	word-spacing: 2px;
	color: #000;
}
.column{
	display: flex;
	flex-direction: column;
	height: 500px;
	border: 1px solid black;
	margin: 5px 5px;
	/*padding: 5px 10px;*/
}
.msg-title{
	line-height: 25px;
	/*margin-left: 5px;
	font-weight: 5px;*/
}
.txtarea{
	width: 99%; 
	height: 80px;
	display: inline-block;
	vertical-align: middle;
	resize: none;
	border-radius: 0px 0px;
	border: 1px solid #cc692f;
}
.widget-content.product-widget-mini{
    position: relative;
    min-height: 160px;
}

h4{
	padding-left: 10px !important;
	padding-right: 0px !important;
}
.custom-img{
    position: absolute;
    right: 10px;
}
.widget>h4{
    height: 30px;
    text-transform: capitalize;
    line-height: 30px;
    font-size: 12px;
    font-weight: bold;
}

.car-price{
    margin-left: 10px;
    margin-right: 5px;
    font-size: 16px;
    color: #000;
}

.widget li {
     padding: 0px !important; 
}
.hidden{
	display: none;
}
.active{
	display: block;
}
.usr{
	margin-top: 5px;
	margin-right: 5px;
}
.admin{
	margin-top: 5px;
	margin-right: 5px;
}
.usr p{
	max-width: 65%;
	padding: 5px;
	text-align: left;
    margin-left: 10px;
    color: #66696a;
    line-height: 17px;
    font-weight: normal;
    font-size: 14px;
    background-color: #f1f3f5;
    padding: 5px 10px;
    /*white-space: pre-line;*/
    word-wrap: break-word;
    border-radius: 3px;
    text-align: left;
    box-sizing: border-box;
    display: inline-block;
}

.admin p{
	float: right;
	max-width: 65%;
	padding: 5px;
	text-align: right;
    margin-right: 10px;
    line-height: 17px;
    color: #333;
    font-weight: normal;
    font-size: 14px;
    background-color: #cfedfb;
    padding: 5px 10px;
    /*white-space: pre-line;*/
    word-wrap: break-word;
    border-radius: 3px;
    text-align: left;
    max-width: 100%;
    box-sizing: border-box;
}
.messages-box{
	overflow-y: auto;
	height: calc(100% - 100px);
}
</style>